# Generated by Django 3.2.21 on 2024-02-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDPAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
