# Generated by Django 3.2.21 on 2024-02-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDPAPP', '0002_auto_20240229_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('roll', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
