# Generated by Django 3.2.21 on 2024-03-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDPAPP', '0003_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='InTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='OutTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='StudentIn',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='StudentOut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='validation',
            field=models.BooleanField(default=False),
        ),
    ]
