# Generated by Django 5.0.3 on 2024-03-18 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDPAPP', '0006_auto_20240302_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='uid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OutRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_time', models.DateTimeField()),
                ('in_time', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_records', to='IDPAPP.student')),
            ],
        ),
    ]
