# Generated by Django 5.0.3 on 2024-03-18 14:48

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDPAPP', '0009_remove_student_otp_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='otp_expiry',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=datetime.datetime(2024, 3, 18, 14, 48, 43, 561639, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
