# Generated by Django 5.0.3 on 2024-03-18 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IDPAPP', '0010_student_otp_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='otp_expiry',
        ),
    ]
