# Generated by Django 5.0.3 on 2024-03-19 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDPAPP', '0012_student_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='otp_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 10, 6, 17, 65582, tzinfo=datetime.timezone.utc)),
        ),
    ]
