# Generated by Django 5.0.3 on 2024-03-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDPAPP', '0013_alter_student_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='otp_expiry',
            field=models.DateField(max_length=200, null=True),
        ),
    ]
