# Generated by Django 5.0.3 on 2024-03-26 09:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDPAPP', '0016_alter_student_otp_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outrecord',
            name='in_time',
        ),
        migrations.RemoveField(
            model_name='outrecord',
            name='out_time',
        ),
        migrations.AddField(
            model_name='outrecord',
            name='InDate',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outrecord',
            name='OutDate',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
