# Generated by Django 5.0.3 on 2024-03-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDPAPP', '0017_remove_outrecord_in_time_remove_outrecord_out_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outrecord',
            name='Flag',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
