# Generated by Django 5.0.3 on 2024-04-01 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IDPAPP', '0018_outrecord_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outrecord',
            name='Flag',
        ),
    ]
