# Generated by Django 5.0.3 on 2024-04-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDPAPP', '0022_outrecord_generalouting_outrecord_homeouting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='showinnotverified',
            field=models.BooleanField(default=True),
        ),
    ]
