# Generated by Django 5.0.3 on 2024-04-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDPAPP', '0023_student_showinnotverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='outrecord',
            name='lateenteryflag',
            field=models.BooleanField(default=False),
        ),
    ]
