# Generated by Django 5.0.3 on 2024-04-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDPAPP', '0024_outrecord_lateenteryflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lateentryflag',
            field=models.BooleanField(default=False),
        ),
    ]
